/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import com.mysql.jdbc.Connection;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import static project.koneksi.con;


/**
 *
 * @author user
 */
public class DataKamar extends javax.swing.JFrame {
    
    
public static Statement stm;
public static ResultSet res;
private JTextField textField;
private String defaultText = "Masukkan Nomor Kamar";
    /**
     * Creates new form DataKamar
     */
    public DataKamar() {
        initComponents();
        tampiltabel();
        koneksimysql();
        tampiltext();
        
        textField = new JTextField();
        txtcarikamar.setText(defaultText);
        txtcarikamar.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent fe) {
                if (txtcarikamar.getText().equals(defaultText)){
                    txtcarikamar.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent fe) {
                if (txtcarikamar.getText().isEmpty()){
                    txtcarikamar.setText(defaultText);
                }
            }
        });
        
    }
    
    
    
    
    public void koneksimysql(){
    try{
        String url="jdbc:mysql://localhost/koswijayanti";
        String user="root";
        String pass="";
        Class.forName("com.mysql.jdbc.Driver");
        con = (Connection) DriverManager.getConnection(url, user, pass);
        stm = (com.mysql.jdbc.Statement) con.createStatement();

    }catch (Exception e){
        System.err.println("koneksi Gagal"+e.getMessage());
    }
}
    
    public void tampiltabel(){
        koneksimysql();
        DefaultTableModel tb = new DefaultTableModel();
        //judul kolom
        tb.addColumn("Nomor Kamar");
        tb.addColumn("Jenis Kamar");
        tb.addColumn("Harga"); 
        tb.addColumn("Status");
        TabelKamar.setModel(tb);
        try{
            //mengambil data dari database
            res=stm.executeQuery("Select * from kamar");
            while (res.next()){
                tb.addRow(new Object[]{
                    res.getString("Nomor_Kamar"),
                    res.getString("Jenis_Kamar"),
                    res.getString("Harga"),
                    res.getString("Status"),
                });
            }
              
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "data gagal ditampilkan" + e.getMessage());
            e.printStackTrace();
        }
    }

private void tampiltext(){
    try {
        String sql = "select * from kamar";
        res = stm.executeQuery(sql);
        while (res.next()){
            ComboNoKamar.addItem(res.getString("Nomor_Kamar"));
        }
    } catch (Exception e) {
    }
}
    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelKamar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        SimpanButton = new javax.swing.JButton();
        JenisKamar = new javax.swing.JTextField();
        Harga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ComboNoKamar = new javax.swing.JComboBox<>();
        cterisi = new javax.swing.JCheckBox();
        ckosong = new javax.swing.JCheckBox();
        txtcarikamar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 402));

        TabelKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Kamar", "Jenis Kamar", "Harga", "Status"
            }
        ));
        jScrollPane1.setViewportView(TabelKamar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 590, 390));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/ooo.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Penyewa");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, -10, 170, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kamar");
        jLabel3.setMaximumSize(new java.awt.Dimension(137, 37));
        jLabel3.setMinimumSize(new java.awt.Dimension(137, 37));
        jLabel3.setPreferredSize(new java.awt.Dimension(137, 37));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 170, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Transaksi");
        jLabel4.setMaximumSize(new java.awt.Dimension(137, 37));
        jLabel4.setMinimumSize(new java.awt.Dimension(137, 37));
        jLabel4.setPreferredSize(new java.awt.Dimension(137, 37));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 170, 80));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/yyy.png"))); // NOI18N
        jLabel5.setText("Admin");
        jLabel5.setMaximumSize(new java.awt.Dimension(137, 37));
        jLabel5.setMinimumSize(new java.awt.Dimension(137, 37));
        jLabel5.setPreferredSize(new java.awt.Dimension(137, 37));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 170, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("DATA KAMAR");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Nomor Kamar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("Jenis Kamar");
        jLabel8.setMaximumSize(new java.awt.Dimension(147, 26));
        jLabel8.setMinimumSize(new java.awt.Dimension(147, 26));
        jLabel8.setPreferredSize(new java.awt.Dimension(147, 26));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        label.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        label.setForeground(new java.awt.Color(102, 51, 0));
        label.setText("Harga");
        label.setMaximumSize(new java.awt.Dimension(147, 26));
        label.setMinimumSize(new java.awt.Dimension(147, 26));
        label.setPreferredSize(new java.awt.Dimension(147, 26));
        label.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        Status.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        Status.setForeground(new java.awt.Color(102, 51, 0));
        Status.setText("Status");
        Status.setMaximumSize(new java.awt.Dimension(147, 26));
        Status.setMinimumSize(new java.awt.Dimension(147, 26));
        Status.setPreferredSize(new java.awt.Dimension(147, 26));
        jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        SimpanButton.setBackground(new java.awt.Color(153, 51, 0));
        SimpanButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        SimpanButton.setForeground(new java.awt.Color(255, 255, 255));
        SimpanButton.setText("Simpan");
        SimpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SimpanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, -1, -1));

        JenisKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisKamarActionPerformed(evt);
            }
        });
        jPanel1.add(JenisKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 390, -1));

        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });
        jPanel1.add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 390, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 0));
        jLabel11.setText("DATA KAMAR");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, -1, -1));

        ComboNoKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH KAMAR ==" }));
        ComboNoKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNoKamarActionPerformed(evt);
            }
        });
        jPanel1.add(ComboNoKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 390, 30));

        buttonGroup1.add(cterisi);
        cterisi.setText("Terisi");
        cterisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cterisiActionPerformed(evt);
            }
        });
        jPanel1.add(cterisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 400, -1, -1));

        buttonGroup1.add(ckosong);
        ckosong.setText("Kosong");
        ckosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckosongActionPerformed(evt);
            }
        });
        jPanel1.add(ckosong, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, -1, -1));

        txtcarikamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcarikamarActionPerformed(evt);
            }
        });
        txtcarikamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcarikamarKeyReleased(evt);
            }
        });
        jPanel1.add(txtcarikamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 590, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/zzzz.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -100, -1, 290));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Template 1 (fix).png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanButtonActionPerformed

String Status = null ;

if(ckosong.isSelected()){
    Status = "Kosong";
}else if(cterisi.isSelected()){
    Status = "Terisi";

}

        try {
            String sql = "UPDATE kamar SET Nomor_Kamar ='"+ComboNoKamar.getSelectedItem()+"',Jenis_Kamar='"+JenisKamar.getText()+"',Harga='"+Harga.getText()+"',Status='"+Status+"' WHERE ID_Kamar= '"+ComboNoKamar.getSelectedIndex()+"'";
            PreparedStatement psht = con.prepareStatement(sql);
            psht.execute();
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Tersimpan");
        }

        
        tampiltabel();
        // TODO add your handling code here:
    }//GEN-LAST:event_SimpanButtonActionPerformed

    private void JenisKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisKamarActionPerformed

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaActionPerformed

    private void ComboNoKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNoKamarActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select * from kamar where Nomor_Kamar = '"+ComboNoKamar.getSelectedItem()+"'";
            res = stm.executeQuery(sql);
            while(res.next()){
                JenisKamar.setText(res.getString("Jenis_Kamar"));
                Harga.setText(res.getString("Harga"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ComboNoKamarActionPerformed

    private void ckosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckosongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckosongActionPerformed

    private void cterisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cterisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cterisiActionPerformed

    private void txtcarikamarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarikamarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel obj = (DefaultTableModel) TabelKamar.getModel();
        TableRowSorter<DefaultTableModel> obj1 = new TableRowSorter<>(obj);
        TabelKamar.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(txtcarikamar.getText()));
    }//GEN-LAST:event_txtcarikamarKeyReleased

    private void txtcarikamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcarikamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarikamarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        new Berandaa().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        new Penyewa().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       this.setVisible(false);
        new DataKamar().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
        new Data_Transaksi().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboNoKamar;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField JenisKamar;
    private javax.swing.JButton SimpanButton;
    private javax.swing.JLabel Status;
    private javax.swing.JTable TabelKamar;
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox ckosong;
    private javax.swing.JCheckBox cterisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField txtcarikamar;
    // End of variables declaration//GEN-END:variables
}