/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Rifqi
 */
public class Login extends javax.swing.JFrame {
private koneksi koneksi;
        
    

 public Login(){
        initComponents();
        use.setVisible(false);
        pw1.setVisible(false);
        pw2.setVisible(false);
 }
 
        
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonlogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        buttonregister = new javax.swing.JButton();
        pw1 = new javax.swing.JLabel();
        use = new javax.swing.JLabel();
        pw2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo (2).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(510, 10, 380, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(540, 100, 250, 240);

        txtusername.setBackground(new java.awt.Color(250, 243, 240));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtusername);
        txtusername.setBounds(610, 420, 420, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 470, 280, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel4.setText("Username :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 410, 290, 50);

        jLabel5.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LOGIN");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 330, 180, 70);

        buttonlogin.setBackground(new java.awt.Color(153, 51, 0));
        buttonlogin.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        buttonlogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonlogin.setText("LOGIN");
        buttonlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonloginMouseClicked(evt);
            }
        });
        buttonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonloginActionPerformed(evt);
            }
        });
        jPanel1.add(buttonlogin);
        buttonlogin.setBounds(880, 550, 150, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Lupa Password?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(540, 640, 250, 42);
        jPanel1.add(txtpassword);
        txtpassword.setBounds(610, 480, 420, 40);

        buttonregister.setBackground(new java.awt.Color(153, 51, 0));
        buttonregister.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        buttonregister.setForeground(new java.awt.Color(255, 255, 255));
        buttonregister.setText("UBAH PASSWORD");
        buttonregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonregisterActionPerformed(evt);
            }
        });
        jPanel1.add(buttonregister);
        buttonregister.setBounds(540, 700, 240, 40);

        pw1.setForeground(new java.awt.Color(255, 0, 0));
        pw1.setText("masukkan password yang benar!");
        jPanel1.add(pw1);
        pw1.setBounds(610, 520, 260, 16);

        use.setForeground(new java.awt.Color(255, 0, 0));
        use.setText("masukkan username anda!");
        jPanel1.add(use);
        use.setBounds(610, 460, 200, 16);

        pw2.setForeground(new java.awt.Color(255, 0, 0));
        pw2.setText("masukkan password anda!");
        jPanel1.add(pw2);
        pw2.setBounds(610, 520, 240, 16);

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(1040, 490, 20, 25);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void buttonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonloginActionPerformed

            try {
                koneksi =new koneksi();
                koneksi.koneksimysql();
            java.sql.Connection c = koneksi.con;
            Statement s = (Statement) c.createStatement();
            
            String sql = "SELECT * FROM admin WHERE Username='"+txtusername.getText()+"'AND Password='"+txtpassword.getText()+"'";
             java.sql.ResultSet rs = s.executeQuery(sql);
             
             
             if(rs.next()){
                 use.setVisible(false);
               pw1.setVisible(false);
                 JOptionPane.showMessageDialog(null, "Login Successfully");
                 this.dispose();
                  new Berandaa().setVisible(true);
                 
             }else{
//                 JOptionPane.showMessageDialog(null, "Wrong Username or password");
                 sql ="select * from admin where Username ='"+txtusername.getText()+"'";
                 rs = s.executeQuery(sql);
                 if (rs.next()){
                     pw1.setVisible(true);
                     use.setVisible(false);
                 } else {
                     use.setVisible(true);
                     pw1.setVisible(false);
                 }
                 
                 
             }
        } catch (Exception e) {
            System.out.println(e);
//            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        
        }
           
    }//GEN-LAST:event_buttonloginActionPerformed

    private void buttonloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonloginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonloginMouseClicked

    private void buttonregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonregisterActionPerformed
        new lupa().setVisible(true);
    }//GEN-LAST:event_buttonregisterActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()){
            txtpassword.setEchoChar((char)0);
        } else {
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonlogin;
    private javax.swing.JButton buttonregister;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel pw1;
    private javax.swing.JLabel pw2;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel use;
    // End of variables declaration//GEN-END:variables
}
